In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\hp\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

### Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dimensional arrays

In [10]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [12]:
n[0,1] = 20

In [13]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [14]:
n[1] = [2,2,2]

In [15]:
n

array([[ 1, 20,  3],
       [ 2,  2,  2],
       [ 7,  8,  9]])

In [16]:
n[:,1]=[5,5,5]

In [17]:
n

array([[1, 5, 3],
       [2, 5, 2],
       [7, 5, 9]])

### Randomly generated arrays

In [18]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [19]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [20]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
b = (10 + (a*2))**2/100

In [22]:
b
print(a,b)

[0 1 2 3 4] [1.   1.44 1.96 2.56 3.24]


In [23]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

### Comparison operations

In [24]:
a >= 2

array([False, False,  True,  True,  True])

In [25]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [26]:
a > b

array([False, False,  True,  True,  True])

In [27]:
a[a>b]

array([2, 3, 4])

### Summarizing operations

In [28]:
a

array([0, 1, 2, 3, 4])

In [29]:
a.min()

0

In [30]:
a.sum()

10

In [31]:
a.mean()

2.0

In [32]:
a.std()

1.4142135623730951

In [33]:
n.sum()

39